### ISSUE TITLE
nodeclipse.org gone? (March 2019)

### ISSUE THREAD

**Issue by pprossi** [Nodeclipse/nodeclipse.github.io#1]
http://nodeclipse.org is down... issnt it the main update site anymore?
https://nodeclipse.org/ does´nt respond also

**Comment by paulvi** [comment]
Almost every year we have problem with expired domain name registration, that @lamb still has to pay for.

If not, resolution of `nodeclipe.org` name stops.

Just checked, that http://www.nodeclipse.org/ is not available.

So use https://nodeclipse.github.io/

**Comment by paulvi** [comment]
ref https://github.com/Nodeclipse/nodeclipse-1/issues/221

**Comment by paulvi** [comment]
Exactly 1 year ago were many clicks
https://marketplace.eclipse.org/content/nodeclipse#group-metrics-tab

![image](https://user-images.githubusercontent.com/1614482/54596212-22f7c800-4a6f-11e9-88f7-fc407331c920.png)

**Comment by paulvi** [comment]
All (or most) of things should use https://nodeclipse.github.io/ now

Not going to care about nodeclise.org domain name.

**Comment by paulvi** [comment]
![image](https://user-images.githubusercontent.com/1614482/68029230-c68da400-fcf1-11e9-8e76-37392d14326c.png)
