### ISSUE TITLE
Cannot install // "No repository found at https://nodeclipse.github.io."

### ISSUE THREAD

**Issue by EagleInNight** [Nodeclipse/nodeclipse.github.io#2]
"No repository found at https://nodeclipse.github.io."

Eclipse 2019-03

**Comment by paulvi** [comment]
well, it should be.

It worked for me.

Can you try again, and confirm that problem still exists?

**Comment by paulvi** [comment]
Oh, should use `https://nodeclipse.github.io/updates/`   

or specific `https://nodeclipse.github.io/updates/gradle-ide-pack/` 
or  `https://nodeclipse.github.io/updates/1/`

note  `https://nodeclipse.github.io`, that is not p2 repository.

Where did you got `https://nodeclipse.github.io.` URL as p2 repo from ?

**Comment by paulvi** [comment]
closing as exactly `https://nodeclipse.github.io` is not p2 repo

**Comment by EagleInNight** [comment]
Just drug'n'drop install button from marketplace

**Comment by paulvi** [comment]
What exact marketplace entry? 

https://marketplace.eclipse.org/user/pverest/listings

**Comment by paulvi** [comment]
OK, now I this is the same issue as https://github.com/Nodeclipse/nodeclipse-1/issues/230
